set(_CATKIN_CURRENT_PACKAGE "traj_planner")
set(traj_planner_VERSION "0.2.1")
set(traj_planner_MAINTAINER "isnow4ever <isnow4ever@todo.todo>")
set(traj_planner_PACKAGE_FORMAT "1")
set(traj_planner_BUILD_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "description")
set(traj_planner_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "description")
set(traj_planner_BUILDTOOL_DEPENDS "catkin")
set(traj_planner_BUILDTOOL_EXPORT_DEPENDS )
set(traj_planner_EXEC_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "description")
set(traj_planner_RUN_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "description")
set(traj_planner_TEST_DEPENDS )
set(traj_planner_DOC_DEPENDS )
set(traj_planner_DEPRECATED "")